{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "tf-registry-api.fullname" . }}
  labels:
    {{- include "tf-registry-api.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # Terraform service discovery
    - match: Host(`{{ .Values.ingress.host }}`) && Path(`/.well-known/terraform.json`)
      kind: Rule
      priority: 120
      services:
        - name: {{ include "tf-registry-api.fullname" . }}
          port: {{ .Values.service.port }}
    # Terraform registry protocol + upload API
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/v1/modules`)
      kind: Rule
      priority: 110
      services:
        - name: {{ include "tf-registry-api.fullname" . }}
          port: {{ .Values.service.port }}
    # Internal health check — routed via nginx proxy (/api/health)
{{- end }}
