apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tf-registry-api.fullname" . }}-data
  labels:
    {{- include "tf-registry-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
